Repository Enqurance/Agile_Frontend, pull requests merged in 2023-04, with the labels that each got.

#8 [feat](): 完成地点搜索组件
  src/assets/PlaceSearch/PlaceSearch.css
  src/assets/PlaceSearch/font1/iconfont.css
  src/assets/PlaceSearch/font1/iconfont.js
  src/assets/PlaceSearch/font1/iconfont.json
  src/assets/PlaceSearch/font1/iconfont.ttf
  src/components/PlaceSearch.vue
  src/global.js
Labels: enhancement

#11 [feat](PlaceSearch): 完成PlaceSearch组件
  src/assets/PlaceSearch/PlaceSearch.css
  src/assets/PlaceSearch/font1/iconfont.css
  src/assets/PlaceSearch/font1/iconfont.js
  src/assets/PlaceSearch/font1/iconfont.json
  src/assets/PlaceSearch/font1/iconfont.ttf
  src/components/PlaceSearch.vue
  src/global.js
Labels: enhancement

#12 [style](global): 改变global.js的导出格式
  src/components/PlaceSearch.vue
  src/global.js
Labels: enhancement

#23 [feat](CICD):Run on PR and Push
  .github/workflows/node_js.yml
Labels: enhancement

#24 [feat](CICD):Update .yml
  .github/workflows/node_js.yml
Labels: enhancement

#38 [chore](.gitignore):Ignore dist dir
  .gitignore
Labels: enhancement

#55 Feature/map homepage
  package-lock.json
  src/components/LoginView.vue
  src/components/MapHomepage.vue
  src/components/MapPinInfo.vue
  src/components/PlaceSearch.vue
  src/components/RegisterView.vue
  src/main.js
Labels: enhancement

#59 Feature/router
  src/components/InforPage.vue
  src/components/PageHeader.vue
  src/router/index.js
  src/router/routerDocument.md
  src/router/routes.js
Labels: enhancement

#69 [chore](CICD):Copy dist
  .github/workflows/node_js.yml
Labels: enhancement

#75 [fix](MapHomepage): debug：地图顶修改时，label不变
  src/components/MapHomepage.vue
  src/components/MapPinInfo.vue
  src/components/PageHeader.vue
Labels: bug

#77 fix(PlaceSearch): fixes #76
  src/components/PlaceSearch.vue
Labels: bug

#79 fix(PlaceSearch): fixes #78
  src/components/PlaceSearch.vue
Labels: bug

#86 [fix](PlaceSearch): closes #85
  src/components/MapHomepage.vue
Labels: bug

#87 [fix](): 修改删除pin，改密码
  src/components/InforPage.vue
  src/components/LoginView.vue
  src/components/MapHomepage.vue
  src/components/RegisterView.vue
Labels: bug

#91 Fix/88
  src/components/InforPage.vue
  src/components/MapHomepage.vue
  src/components/MapPinAdd.vue
  src/components/MapPinInfo.vue
  src/components/PlaceSearch.vue
  src/global.js
Labels: bug

#97 [fix](Pin): 添加选择pin类型
  src/components/InforPage.vue
  src/components/LoginView.vue
  src/components/MapHomepage.vue
Labels: bug

#99 [feat](Verification):Add veri button
  package-lock.json
  package.json
  src/App.vue
  src/components/ManVerify.vue
Labels: enhancement

#100 Fix/98
  src/components/MapHomepage.vue
  src/components/MapPinInfo.vue
Labels: bug, enhancement

#101 [feat](Info): 增添修改密码退出登录并删除token功能
  src/App.vue
  src/components/InforPage.vue
  src/components/ManVerify.vue
  src/components/MapHomepage.vue
Labels: enhancement
